[theme]

# Primary accent for interactive elements
primaryColor = '#f0c9fd'

# Background color for the main content area
backgroundColor = '#342d37'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3a2c40'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "monospace"
font = "monospace"
